basePath: /
definitions:
  models.Bookmark:
    properties:
      id:
        type: integer
      name:
        type: string
      tag:
        type: string
      url:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Bookmark API
  version: "1.0"
paths:
  /bookmark:
    delete:
      responses:
        "204":
          description: No Content
      summary: Delete all bookmarks
      tags:
      - bookmarks
    get:
      parameters:
      - description: Filter by name
        in: query
        name: name
        type: string
      - collectionFormat: csv
        description: Filter by tag
        in: query
        items:
          type: string
        name: tag
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Bookmark'
            type: array
      summary: List bookmarks
      tags:
      - bookmarks
    post:
      consumes:
      - application/json
      parameters:
      - description: Bookmark data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Bookmark'
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a bookmark
      tags:
      - bookmarks
  /bookmark/{id}:
    delete:
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete a bookmark
      tags:
      - bookmarks
    get:
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Bookmark'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a bookmark
      tags:
      - bookmarks
    put:
      consumes:
      - application/json
      parameters:
      - description: Bookmark ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bookmark data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Bookmark'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a bookmark
      tags:
      - bookmarks
swagger: "2.0"
